### PR TITLE
implement chunked encryption for ssl provider

### PR DESCRIPTION
**Pull request by timogoebel**
With the current ssl encryption implementation you will get the error message "data too large for key size (OpenSSL::PKey::RSAError)" when trying to encrypt large data. This can be fixed by encrypting the data in chunks.

@Thomas-Gelf: What do you think?

### CODE REVIEW

**Comment by timogoebel** [comment]
@duritong : Any comments on this PR? What do you think?

**Comment by duritong** [comment]
I didn't yet look deep enough into it to make a decision and hoped @Thomas-Gelf will comment on it. However, I will certainly take the time and look into it in the next days.

**Comment by timogoebel** [comment]
Thanks, @duritong!  
@Thomas-Gelf already had a look on this and found it ok.

**Comment by Thomas-Gelf** [comment]
Sorry for the delay, and yes: I did :) As RSA only allows to encrypt string up to a maximum length of "key size minus 11 bytes" you would otherwise have no chance to encrypt another RSA key of the same length. Chunked encoding is one of the current best practices to cope with this limitation.

Generating another (encrypted) random key for symmetric encryption would be another option, but that one doesn't really fit our needs, especially when working with multiple Puppet masters sharing a common database.

Cheers,
Thomas

**Comment by duritong** [comment]
So the only remaining question is, whether we should have a test for that. I can try adding one if you need assistance.

**Comment by timogoebel** [comment]
@duritong : Thanks for reviewing. I could add a test for the chunksize, that tests whether it it 4096-11. What other testcases would you suggest?

**Comment by duritong** [comment]
I added a testcase that tries to store a 4096 long password. This test fails without your patch.

**Pull request merged**
